#Oracle配置
#spring:
#  datasource:
#    driverClassName: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@127.0.0.1:1521:guns
#    username: root
#    password: root
#    filters: wall,mergeStat

#SQLServer配置
#spring:
#  datasource:
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=guns
#    username: root
#    password: root
#    filters: wall,mergeStat

#PostgreSQL配置
#spring:
#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://127.0.0.1:5432/guns
#    username: root
#    password: root
#    filters: wall,mergeStat

# Mysql数据库
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-2ze30o1742o28135yno.mysql.rds.aliyuncs.com:3306/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT
    username: guns
    password: 123456
    filters: wall,mergeStat

  # 邮件发送配置（改为自己的账号和密码）
  mail:
    host: smtp.outlook.com
    port: 587
    username: PeterYanMei@outlook.com
    password: xiaomei520..

# 邮件发送（改为自己的账号）
mail:
  from: PeterYanMei@outlook.com
